version: '3.8'
services:
  vocbench3:
    build:
      context: 13.0.0
      args:
        vb_version: ${VB_VERSION}
        st_version: ${ST_VERSION}
    ports:
    - "1979:1979"
    volumes:
     - type: bind
       source: ./volumes/stdata
       target: /opt/vocbench3/data
    links:
    - graphdb
  graphdb:
    build:
      context: ./helpers/graphdb-with-st-sails
      args:
        vb_version: ${VB_VERSION}
        st_version: ${ST_VERSION}
        gdb_version: ${GDB_VERSION}
    ports:
     - "127.0.0.1:7200:7200"
    volumes:
     - type: bind
       source: ./volumes/gdbhome
       target: /opt/graphdb/home